CREATE DATABASE EXAMEN1
use EXAMEN1

CREATE TABLE ARTICULOS(
ARTID INT NOT NULL,
ARTNOMBRE NVARCHAR,
ARTPRECIO MONEY,
ARTPAQUETE INT NOT NULL
)
GO
CREATE TABLE ENVIOS(
BODID INT NOT NULL,
FOLIO INT NOT NULL,
FECHA DATE,
ARTID INT NOT NULL,
CANTIDAD INT,
PRECIO MONEY
)
GO
CREATE TABLE BODEGAS(
BODID INT NOT NULL,
BODNOMBRE NVARCHAR (40),
BODDOMICILIO NVARCHAR (40),
TIPOID INT NOT NULL
)
GO
CREATE TABLE TIPOS(
TIPOID INT NOT NULL,
TIPONOMBRE NVARCHAR(40)
)
GO

ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ARTICULOS PRIMARY KEY (ARTID)
GO
ALTER TABLE ENVIOS ADD CONSTRAINT PK_ENVIOS PRIMARY KEY (FOLIO,BODID)
GO
ALTER TABLE BODEGAS ADD CONSTRAINT PK_BODEGAS PRIMARY KEY (BODID)
GO
ALTER TABLE TIPOS ADD CONSTRAINT PK_TIPOS PRIMARY KEY (TIPOID)
GO

ALTER TABLE ENVIOS ADD
CONSTRAINT FK_ENVIOS_BODEGAS FOREIGN KEY (BODID) REFERENCES BODEGAS (BODID),
CONSTRAINT FK_ENVIOS_ARTICULOS FOREIGN KEY (ARTID) REFERENCES ARTICULOS (ARTID)
GO
ALTER TABLE BODEGAS ADD
CONSTRAINT FK_BODEGAS_TIPOS FOREIGN KEY (TIPOID) REFERENCES TIPOS (TIPOID)
GO
ALTER TABLE ARTICULOS ADD
CONSTRAINT FK_ARTICULOS_ARTICULOS FOREIGN KEY (ARTPAQUETE) REFERENCES ARTICULOS (ARTID)

ALTER TABLE BODEGAS
ADD UNIQUE (TIPOID)

ALTER TABLE ARTICULOS ADD
CONSTRAINT CC_PRECIO_ARTICULOS CHECK (ARTPRECIO>0)
GO
ALTER TABLE ENVIOS ADD 
CONSTRAINT CC_PRECIO_ENVIOS CHECK (PRECIO>0)


