CREATE DATABASE PROYECTO_INDICES
DROP TABLE ARTICULOS
CREATE TABLE ARTICULOS(
artID INT NOT NULL PRIMARY KEY,
artNombre varchar(20),
artDescripcion varchar(100),
artPrecio money,
artActivo bit,
artStock numeric(12,2),
artFechaIngreso datetime
)

CREATE TABLE PEDIDOS(
folio int NOT NULL,
fecha datetime,
cantidad numeric(12,2),
precio money,
cliID int NOT NULL,
artID int NOT NULL
FOREIGN KEY (cliID) REFERENCES CLIENTES(cliID),
FOREIGN KEY (artID) REFERENCES ARTICULOS(artID)
)

CREATE TABLE CLIENTES(
cliID int NOT NULL PRIMARY KEY,
cliNombre varchar(30),
cliApellidos varchar (100),
cliDomicilio varchar (100),
cliCP char(5),
cliSexo char(1),
cliCelular varchar(100),
cliFechaNac datetime
)
SELECT*FROM ARTICULOS
--PRIMARY KEY
ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ARTICULO PRIMARY KEY (artID)
go
SELECT*FROM ARTICULOS

SET STATISTICS TIME ON

SET STATISTICS IO ON

--2.- CREAR LOS SIGUIENTES INDICES AGRUPADOS:
--INDICE AGRUPADO – ARTNOMBRE WHERE ARTNOMBRE LIKE ‘%CARLOS%’ AND ARTDESCRIPCION LIKE ‘%AS%’
DROP INDEX IX_CLUSTEREDARTICULOS ON DBO.ARTICULOS 

CREATE CLUSTERED INDEX IX_CLUSTEREDARTICULOS ON DBO.ARTICULOS (artNombre asc) 
WITH(SORT_IN_TEMPDB= OFF, DROP_EXISTING= OFF, FILLFACTOR=90) ON [PRIMARY]

SELECT * FROM [dbo].[ARTICULOS] WHERE ARTNOMBRE LIKE '%CARLOS%' AND ARTDESCRIPCION LIKE '%AS%'
GO
--INDICE AGRUPADO – ARTPRECIO WHERE ARTPRECIO > 50 AND ARTDESCRIPCION LIKE ‘%AS%’
DROP INDEX IX_CLUSTEREDARTICULOS ON DBO.ARTICULOS 

CREATE CLUSTERED INDEX IX_CLUSTEREDARTICULOS ON DBO.ARTICULOS (artPrecio asc) 

SELECT * FROM [dbo].[ARTICULOS] WHERE ARTPRECIO > 50 AND ARTDESCRIPCION LIKE '%AS%'
GO
--INDICE AGRUPADO – ARTSTOCK WHERE ARTSTOCK = 0 AND ARTDESCRIPCION LIKE ‘%AS%’
DROP INDEX IX_CLUSTEREDARTICULOS ON DBO.ARTICULOS 

CREATE CLUSTERED INDEX IX_CLUSTEREDARTICULOS ON DBO.ARTICULOS (artStock asc) 

SELECT * FROM [dbo].[ARTICULOS] WHERE ARTSTOCK = 0 AND ARTDESCRIPCION LIKE '%AS%'

--INDICE AGRUPADO - ARTFECHAINGRESO WHERE ARTFECHAINGRESO = ‘1-1-2014’ AND ARTDESCRIPCION LIKE ‘%AS%’
DROP INDEX IX_CLUSTEREDARTICULOS ON DBO.ARTICULOS 

CREATE CLUSTERED INDEX IX_CLUSTEREDARTICULOS ON DBO.ARTICULOS (artFechaIngreso asc) 
WITH(SORT_IN_TEMPDB= OFF, DROP_EXISTING= OFF, FILLFACTOR=90) ON [PRIMARY]

SELECT * FROM [dbo].[ARTICULOS] WHERE ARTFECHAINGRESO = '1-1-2014' AND ARTDESCRIPCION LIKE '%AS%'
GO
--2.- CREAR LOS SIGUIENTES INDICES NO AGRUPADOS Y VERIFICAR:
--INDICE NO AGRUPADO- ARTNOMBRE
CREATE NONCLUSTERED INDEX IX_NonClusteredArticulos ON ARTICULOS (artNombre)
WITH (ONLINE = ON , FILLFACTOR=90 )

SELECT * FROM [dbo].[ARTICULOS] WHERE ARTNOMBRE LIKE '%PEDRO%' AND ARTDESCRIPCION LIKE '%ASA%'
GO
--INDICE NO AGRUPADO- ARTNOMBRE INCLUDE (ARTID, ARTDESCRIPCION)
DROP INDEX IX_NonClusteredArticulos ON ARTICULOS

CREATE NONCLUSTERED INDEX IX_NonClusteredArticulos ON ARTICULOS (artNombre) INCLUDE (artID, artDescripcion)
WITH (ONLINE = ON , FILLFACTOR=90 )

SELECT * FROM [dbo].[ARTICULOS] WHERE ARTNOMBRE LIKE '%PEDRO%' AND ARTDESCRIPCION LIKE '%ASA%'
GO

--INDICE NO AGRUPADO- ARTNOMBRE INCLUDE (ARTID, ARTDESCRIPCION, ARTPRECIO, ARTACTIVO)
DROP INDEX IX_NonClusteredArticulos ON ARTICULOS

CREATE NONCLUSTERED INDEX IX_NonClusteredArticulos ON ARTICULOS (artNombre) INCLUDE (artID, artDescripcion, artActivo)
WITH (ONLINE = ON , FILLFACTOR=90 )

SELECT * FROM [dbo].[ARTICULOS] WHERE ARTNOMBRE LIKE '%PEDRO%' AND ARTDESCRIPCION LIKE '%ASA%'
GO

--INDICE NO AGRUPADO- ARTNOMBRE INCLUDE (ARTID, ARTDESCRIPCION, ARTPRECIO, ARTACTIVO, ARTSTOCK, ARTFECHAINGRESO)
DROP INDEX IX_NonClusteredArticulos ON ARTICULOS

CREATE NONCLUSTERED INDEX IX_NonClusteredArticulos ON ARTICULOS (artNombre) INCLUDE (artID, artDescripcion, 
artActivo, artFechaIngreso)
WITH (ONLINE = ON , FILLFACTOR=90 )

SELECT * FROM [dbo].[ARTICULOS] WHERE ARTNOMBRE LIKE '%PEDRO%' AND ARTDESCRIPCION LIKE '%ASA%'
GO
--3.- Crear las siguientes consultas :

--a.- Where p.folio < 500 and A.artnombre like ‘%cas%’

SELECT * FROM [dbo].[ARTICULOS] A 
INNER JOIN PEDIDOS p on p.artID= a.artID
INNER JOIN CLIENTES c on p.cliID= c.cliID
where p.folio < 500 and A.artnombre like '%cas%'

--b.- Where p.folio < 500 and c.clinombre like ‘%cas%’
SELECT * FROM [dbo].[ARTICULOS] A 
INNER JOIN PEDIDOS p on p.artID= a.artID
INNER JOIN CLIENTES c on p.cliID= c.cliID
Where p.folio < 500 and c.clinombre like '%cas%'

--c.- Where p.folio < 500 and A.artnombre like ‘%cas%’ and c.clinombre like ‘%cas%’
SELECT * FROM [dbo].[ARTICULOS] A 
INNER JOIN PEDIDOS p on p.artID= a.artID
INNER JOIN CLIENTES c on p.cliID= c.cliID
Where  p.folio < 500 and A.artnombre like '%cas%' and c.clinombre like '%cas%'
