USE adminBD

SELECT ID, FIRSTNAME, LASTNAME
FROM Students
WHERE FIRSTNAME='AARON'
ORDER BY FIRSTNAME ASC, LASTNAME

SELECT FIRSTNAME, LASTNAME FROM Students WHERE FIRSTNAME='ALI'

SELECT FIRSTNAME, LASTNAME FROM Students WHERE LASTNAME='HADI'

SELECT FIRSTNAME, LASTNAME FROM Students
WHERE FIRSTNAME='AARON'
ORDER BY FIRSTNAME ASC, LASTNAME DESC

SELECT FIRSTNAME, LASTNAME FROM Students
WHERE FIRSTNAME='AARON'
ORDER BY FIRSTNAME DESC, LASTNAME ASC

SELECT FIRSTNAME, LASTNAME FROM Students
WHERE FIRSTNAME='AARON'
ORDER BY LASTNAME DESC, FIRSTNAME ASC 

SELECT FIRSTNAME, LASTNAME FROM Students
WHERE FIRSTNAME='AARON'
ORDER BY ID

SELECT FIRSTNAME, LASTNAME FROM Students
WHERE FIRSTNAME='AARON'
ORDER BY ID, LASTNAME DESC
---
DROP  INDEX IX_STUDENT ON DBO.STUDENTS 
CREATE NONCLUSTERED INDEX IX_STUDENT ON DBO.STUDENTS (FIRSTNAME)

CREATE NONCLUSTERED INDEX IX_STUDENT ON DBO.STUDENTS (FIRSTNAME, LASTNAME)

CREATE NONCLUSTERED INDEX IX_STUDENT ON DBO.STUDENTS (FIRSTNAME ASC, LASTNAME DESC)