create database Ventas
go
use Ventas

CREATE TABLE Clientes(
cte INT PRIMARY KEY NOT NULL,
nombre varchar (50),
domicilio varchar(50),
)
go
CREATE TABLE Articulos(
clave INT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (50)
)
go

--CREAR EL INICIO DE SESION "MARIO"
CREATE LOGIN Mario WITH PASSWORD= '123'
MUST_CHANGE, CHECK_EXPIRATION= ON

--VALIDAR LAS CARACTERISTICAS DE MARIO
sp_helplogins Mario

--CAMBIAR AL IS Mario LA BDE VENTAS COMO BD DEFAULT
ALTER LOGIN Mario
WITH DEFAULT_DATABASE= MASTER

--DARLE ACCESO AL IS MARIO A LA BD VENTAS
USE Ventas
CREATE USER Mario
sp_helplogins Mario





