--SE CREA UNA INSTANTANEA ANTES DE UN PROCESO IMPORTANTE

CREATE DATABASE NORTHWIND_INSTANTANEA ON
(NAME=NORTHWINDNEW, FILENAME=
'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NORTHWIND_INSTANTANEA.ss')
AS SNAPSHOT OF NORTHWINDNEW;

--SE HACE UNA MOIFICACION DE DATOS
USE NorthwindNew
UPDATE PRODUCTS SET UNITPRICE=20

--SE RESTAURA A PARTIR DE UNA INSTANTANEA
USE master
RESTORE DATABASE NORTHWINDNEW FROM DATABASE_SNAPSHOT='NORTHWIND_INSTANTANEA';

--SE VERIFICA SI SE RECUPERO LA INSTANTANEA
USE NorthwindNew
SELECT*FROM PRODUCTS

--ES NECESARIO QUITAR LA ISNTANTANEA PARA PODER REALIZAR OTRAS CS
DROP DATABASE NORTHWIND_INSTANTANEA

--NO SE PUEDE REALIZAR CS MIESNTRAS EXISTA LA ISNTANTANEA
sp_addumpdevice 'disk', RespaldoNuevo,
'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\RespaldoNuevo.bak'

use master
backup database NorthwindNew to RespaldoNuevo
with init, format, name='CSC con RT', description= 'CSC de la bd NorthwindNew'
