--ORIGEN
--SE TIENE QUE DESACOPLAR PARA PODERLA COPIAR
sp_detach_db NorthwindLog

--1.-COPIAR A UNA CARPETA LOS ARCHIVOS NORTHWIND.MDF Y NORTHWIND_LOG.LDF
--2.Y CAMBIARLE LOS NOMBRES A NORTHWIND2023.MDF Y NORTHWIND2023_LOG.LDF
--3. COPIAR LOS ARCHIVOS NORTHWIND2023 Y NORTHWIND2023_LOG.LDF
--A LA CARPETA C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA
CREATE DATABASE PRUEBA2023 ON
(NAME= 'PRUEBA2023', FILENAME=
'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA'),
(NAME='PRUEBA2023', FILENAME=
'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA')
FOR ATTACH;

sp_helpdb PRUEBA2023

--VERIFICAR QUE SE COPIO LA BD NORTHWIND
use PRUEBA2023
select*from Orders
select*from Products

--ORIGEN
--SE ACOPLA NUEVAMENTE LA BD NORTHWIND
sp_attach_db @dbname='Northwind'
@filename1=
'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA'
@filename2='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA'

use Northwind
select*from orders 




