--TABLA QUE SE LLENARA DENTRO DEL TRIGGER DDL SOBRE LA BASE DE DATOS
CREATE TABLE DBO.LOGCAMBIOSDDLSERVIDOR(
CLAVE INT IDENTITY PRIMARY KEY,
FECHA DATETIME NOT NULL CONSTRAINT DF_LOGCAMBIOSDDL_FECHACAMBIO DEFAULT (GETDATE()),
INICIOSESION VARCHAR(500) NOT NULL,
ACCION VARCHAR (500) NOT NULL,
SENTENCIA VARCHAR (MAX)NOT NULL,
DETALLEEVENTO XML NOT NULL);
GO

CREATE TRIGGER TRDB_SERVIDOR
ON ALL SERVER DDL_SERVER_SECURITY_EVENTS
AS
BEGIN
     SET NOCOUNT ON;
	 --DECLARACION DE VARIABLES DE PROCESO
	 DECLARE @INFOEVENTO XML, @ACCION VARCHAR(500), @OBJETO VARCHAR (500), @SENTENCIA VARCHAR(MAX);
	 --1.CAPTURA DE EVENTO VARIABLE PRINCIPAL
	 SET @INFOEVENTO=EVENTDATA();
	 --2.CONSUMIR INFORMACION EN VARIABLES SECUNDARIAS USANDO XQUERY
	 --CAPTURA LA ACCION DDL(SI ES CREATE, ALTER, DROP)
	 SET @ACCION=@INFOEVENTO.VALUE('(/EVENT_INSTANCE/EVENTTYPE)[1]','VARCHAR (500)');

	 --CAPTURA LA SENTENCIA EJECUTADA
	 SET @SENTENCIA=@INFOEVENTO.VALUE('(/EVENT_INSTANCE/TSQLCOMMAND)[1]','NVARCHAR(MAX)');

	 --3 ALMACENAR DETALLES DE LA ACCION EN TABLA LOG
END 
GO